### ISSUE TITLE
Support given length for duplications, just like for deletions.

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantValidator#216]
VV handles given lengths for deletions nicely, like [`NC_000017.10:g.12345678_12345680del3`](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000017.10%3Ag.12345678_12345680del3/all/all/True/False?content-type=application%2Fjson). VV even checks if 3 matches the given positions, as [del4 returns an error here](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000017.10%3Ag.12345678_12345680del4/all/all/True/False?content-type=application%2Fjson). However, when replacing `del` by `dup` all support ends and [VV returns an error](https://www35.lamp.le.ac.uk/LOVD/lovd/GRCh37/NC_000017.10%3Ag.12345678_12345680dup3/all/all/True/False?content-type=application%2Fjson):

```json
{
  "NC_000017.10:g.12345678_12345680dup3":{
    "NC_000017.10:g.12345678_12345680dup3":{
      "genomic_variant_error":"NC_000017.10:g.12345678_12345680dup3: char 36: expected EOF",
    },
    "flag":"genomic_variant_warning"
  }
}
```

When supporting `del3`, it would be nice to support `dup3` as well :wink:

**Comment by PeteCausey-Freeman** [comment]
I dont want to support either. Neither are compliant. The coordinates give the range. :). FYI, expect both to return errors! Hahaha

**Comment by PeteCausey-Freeman** [comment]
or even Mwa  ha hahahhaa

**Comment by PeteCausey-Freeman** [comment]
This will be improved though "char 36: expected EOF"

**Comment by ifokkema** [comment]
Errrr... so first you improved support in #180, and now you're removing it? Hmm... why? Checking if the length matches the positions is an additional quality check, and I'm actually very happy VV and the hgvs module that it uses help me check these. If the numbers are OK, they are removed by VV and thus by my checking script; if they're not OK, I know I need to double-check the data.

**Comment by PeteCausey-Freeman** [comment]
Oh yeah. Ok. I'll go woth your suggestion and raise a warning. 

You think I can remember what I'm doing at the moment? ;)

**Comment by PeteCausey-Freeman** [comment]
So, agreed, let's see if we can do this for duplications too :)

**Comment by ifokkema** [comment]
Haha OK, so I nearly got a heart attack yesterday after seeing your evil laughter :smiling_imp:, but I'm happy again now :sweat_smile:

**Comment by PeteCausey-Freeman** [comment]
Ity OK, Ive not gone evil, just slowly mad. See you in the mental hospital soon! :)

**Comment by ifokkema** [comment]
That means you'll need to join me here because they've already got me :laughing:

**Comment by PeteCausey-Freeman** [comment]
Right @ifokkema . I have been given compassionalte leave for good behaviour. On it!

**Comment by PeteCausey-Freeman** [comment]
this is going to require amendments to https://github.com/openvar/vv_hgvs
Not necessarily a quick job. Will put on hold temporality

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/commit/029f439801ad707d37cd77c4452bdbccdb25b104 closes the issue

Note @ifokkema , these changes will not show on the live servers yet. I will update after I have fixed a few more little bugs.

Cheers

Pete

**Comment by ifokkema** [comment]
Beautiful, thanks a lot mate!! :smile: :+1:

**Comment by PeteCausey-Freeman** [comment]
Yeah, just found out all my servers need to be migrated onto a newer server platform. I sense a headache in the force. I'll build your new dev server first because it will be the easiest potentially and give me a feel for the new platform. 

Not sure if you will need a new base URL or not. I will see if IT can ad an alias

**Comment by ifokkema** [comment]
Oh, that's horrible - server migration is the worst!!!
Don't worry too much about the URL - it's configurable on our end :wink:

**Comment by ifokkema** [comment]
While we're at it - just like #252, this fix also doesn't actually seem fixed.
This still throws an "expected EOF" error;

https://rest.variantvalidator.org/LOVD/lovd/GRCh37/NC_000017.10%3Ag.12345678_12345680dup3/all/all/True/False?content-type=application%2Fjson

**Comment by PeteCausey-Freeman** [comment]
Right, I have  feeling that I fixed these for VV but not for VF. Must have gotten confused.

**Comment by PeteCausey-Freeman** [comment]
Leave it with me. I remember the conversations but cannot remember what I did about it.

**Comment by PeteCausey-Freeman** [comment]
OK, IE is now resolved and the output will be 
```json
{
    "NC_000017.10:g.12345678_12345680dup3": {
        "errors": [],
        "flag": "genomic_variant_warning",
        "NC_000017.10:g.12345678_12345680dup3": {
            "p_vcf": "17:12345677:A:ATAT",
            "g_hgvs": "NC_000017.10:g.12345681_12345683dup",
            "selected_build": "GRCh37",
            "genomic_variant_error": "NC_000017.10:g.12345678_12345680dup3 updated to NC_000017.10:g.12345681_12345683dup",
            "hgvs_t_and_p": {
                "intergenic": {
                    "alt_genomic_loci": null
                }
            }
        }
    },
    "metadata": {
        "variantvalidator_version": "1.0.5.dev228+gee3fee4.d20211116",
        "variantvalidator_hgvs_version": "2.0.1.dev2+g58fc52a",
        "vvta_version": "vvta_2021_2",
        "vvseqrepo_db": "VV_SR_2021_2/master",
        "vvdb_version": "vvdb_2021_4",
        "variantformatter_version": "1.0.2.dev20+ge725d86.d20211116"
    }
}
``` 
for https://rest.variantvalidator.org/LOVD/lovd/GRCh37/NC_000017.10%3Ag.12345678_12345680dup3/all/all/False/True?content-type=application%2Fjson. Gonna fix the other bugs then update server

**Comment by PeteCausey-Freeman** [comment]
Testing on dev
http://127.0.0.1:5000/LOVD/lovd/GRCh37/NC_000017.10%3Ag.12345678_12345680del3/all/all/False/True?content-type=application%2Fjson 

```json
{
  "NC_000017.10:g.12345678_12345680del3": {
    "NC_000017.10:g.12345678_12345680del3": {
      "g_hgvs": "NC_000017.10:g.12345681_12345683del",
      "genomic_variant_error": "NC_000017.10:g.12345678_12345680del3 updated to NC_000017.10:g.12345681_12345683del",
      "hgvs_t_and_p": {
        "intergenic": {
          "alt_genomic_loci": {
            "grch37": {},
            "grch38": {},
            "hg19": {},
            "hg38": {}
          },
          "primary_assembly_loci": {
            "grch37": {
              "NC_000017.10": {
                "hgvs_genomic_description": "NC_000017.10:g.12345681_12345683del",
                "vcf": {
                  "alt": "A",
                  "chr": "17",
                  "pos": "12345677",
                  "ref": "ATAT"
                }
              }
            },
            "grch38": {
              "NC_000017.11": {
                "hgvs_genomic_description": "NC_000017.11:g.12442364_12442366del",
                "vcf": {
                  "alt": "A",
                  "chr": "17",
                  "pos": "12442360",
                  "ref": "ATAT"
                }
              }
            },
            "hg19": {
              "NC_000017.10": {
                "hgvs_genomic_description": "NC_000017.10:g.12345681_12345683del",
                "vcf": {
                  "alt": "A",
                  "chr": "chr17",
                  "pos": "12345677",
                  "ref": "ATAT"
                }
              }
            },
            "hg38": {
              "NC_000017.11": {
                "hgvs_genomic_description": "NC_000017.11:g.12442364_12442366del",
                "vcf": {
                  "alt": "A",
                  "chr": "chr17",
                  "pos": "12442360",
                  "ref": "ATAT"
                }
              }
            }
          }
        }
      },
      "p_vcf": "17:12345677:ATAT:A",
      "selected_build": "GRCh37"
    },
    "errors": [],
    "flag": "genomic_variant_warning"
  },
  "metadata": {
    "variantformatter_version": "1.0.2.dev20+ge725d86.d20211116",
    "variantvalidator_hgvs_version": "2.0.1.dev2+g58fc52a",
    "variantvalidator_version": "1.0.5.dev228+gee3fee4.d20211116",
    "vvdb_version": "vvdb_2021_4",
    "vvseqrepo_db": "VV_SR_2021_2/master",
    "vvta_version": "vvta_2021_2"
  }
}
```

**Comment by PeteCausey-Freeman** [comment]
Think this can now close

**Comment by ifokkema** [comment]
Looks great, thank you! The only thing slightly out of line is that the error "Trailing digits are not permitted in HGVS variant descriptions (...)" is only given when the length does *not* match the given variant positions. If it *does*, then the error is *not* given. So in a sense, it's not necessary I guess. But, I'll leave that up to you :hand_over_mouth:

**Comment by PeteCausey-Freeman** [comment]
Hmm, might be determined by what is actually possible. Will look in the morning
